import type { Metadata } from "next";
import { Pixelify_Sans } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar"
import { GameProvider } from "@/context/GameContext"

const pixelifySans = Pixelify_Sans({
  subsets: ["latin"],
  weight: ["400", "700"], // přidej váhy, ať to vidíš
  variable: "--font-pixelify-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixelifySans.variable} antialiased`}
      >
        <GameProvider>
          <NavBar />
          {children}
        </GameProvider>
      </body>
    </html>
  );
}
